### ISSUE TITLE
Documentation provider don't work when hover

### ISSUE THREAD

**Issue by i582** [VKCOM/kphpstorm#36]
## Actual
<img width="427" alt="Снимок экрана 2022-08-20 в 16 24 04" src="https://user-images.githubusercontent.com/51853996/185748162-0f62496b-518d-4087-b60a-61aa54b5b341.png">

## Expected
<img width="421" alt="Снимок экрана 2022-08-20 в 16 24 18" src="https://user-images.githubusercontent.com/51853996/185748169-f73fe458-6398-4132-8a12-00ba87ebd32b.png">

**Comment by Danil42Russia** [comment]
@i582, close this issue?

**Comment by i582** [comment]
Yep
